// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAoajGcMprnmNYBCsuwAs38fwS9dJJ4s',
    appId: '1:763918127028:web:a303e49070251bd4ebece1',
    messagingSenderId: '763918127028',
    projectId: 'resourcehub-afb09',
    authDomain: 'resourcehub-afb09.firebaseapp.com',
    storageBucket: 'resourcehub-afb09.appspot.com',
    measurementId: 'G-QLS4MS55Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRt3XESNAaZbID2CaJr8upirZNBaDF0Rc',
    appId: '1:763918127028:android:e8a341d6b4cafb66ebece1',
    messagingSenderId: '763918127028',
    projectId: 'resourcehub-afb09',
    storageBucket: 'resourcehub-afb09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJY-GhTj6CJ6zaOl-o1myf2ix3sHugE0Y',
    appId: '1:763918127028:ios:6eb93ea7e6d5b714ebece1',
    messagingSenderId: '763918127028',
    projectId: 'resourcehub-afb09',
    storageBucket: 'resourcehub-afb09.appspot.com',
    iosBundleId: 'com.cretech.resource',
  );
}
